name: resonix
description: "A self-hosted music player for your personal music collection."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.1
  http: ^1.3.0
  dio: ^5.8.0+1
  provider: ^6.1.2
  audio_service: ^0.18.17
  just_audio: ^0.9.46
  google_nav_bar: ^5.0.7
  rxdart: ^0.28.0
  just_audio_background: ^0.0.1-beta.15
  shimmer: ^3.0.0
  palette_generator: ^0.3.3+5
  visibility_detector: ^0.4.0+2
  flutter_spinkit: ^5.2.1
  flutter_volume_controller: ^1.3.3
  cached_network_image: ^3.4.1
  interactive_slider: ^0.5.1
  marquee: ^2.3.0
  haptic_feedback: ^0.5.1+1
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/sm_logo_x512.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/sm_logo_x512.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/sm_logo_x512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fl_resonix_x512.png
    - assets/sq_logo_x512.png
    - assets/sm_logo_x512.png